from .mit_news_scraper import MITNewsScraper
from .neuron_daily_scraper import NeuronDailyScraper
from .google_research_scraper import GoogleResearchScraper
from .tech_republic_scraper import TechRepublicScraper
from .tldr_news_scraper import TLDRNewsScraper
from .openai_news_scraper import OpenAINewsScraper
from .nvidia_dev_blog_scraper import NVIDIADevBlogScraper