POSITIVE_KEYWORDS = [
    "deep learning",
    "large language models",
    "generative AI",
    "foundation models",
    "AI agents",
    "retrieval augmented generation",
    "RAG systems",
    "natural language processing",
    "computer vision",
    "vision-language models",
    "multimodal models",
    "document understanding",
    "semantic search",
    "enterprise AI",
    "AI platforms",
    "AI infrastructure",
    "cloud computing for AI",
    "cybersecurity AI",
    "explainable AI",
    "interpretable machine learning",
    "fairness in AI",
    "AI policy",
    "MLOps",
    "reinforcement learning",
    "new AI features"
]

NEGATIVE_KEYWORDS = [
    "theoretical machine learning",
    "learning theory",
    "generalization bounds",
    "convergence proofs",
    "optimization theory",
    "novel loss function",
    "theoretical architecture",
    "synthetic benchmark",
    "toy dataset",
    "AI for physics",
    "AI for chemistry",
    "AI for biology",
    "game",
    "gaming AI",
    "graphics rendering",
    "entertainment AI",
    "healthcare AI",
    "medical imaging AI",
    "clinical decision support",
    "drug discovery AI",
    "algorithmic trading",
    "quantitative finance",
    "cryptocurrency",
    "blockchain",
    "autonomous vehicles",
    "robotics",
    "self-driving cars",
    "drones",
    "financial modeling",
    "risk assessment",
    "acquisition",
    "mergers",
    "startup funding",
    "animation",
]
